-- ============================================================
-- TECNOISO CRM — Schema + Dados iniciais
-- Execute no SQL Editor do Supabase
-- ============================================================

-- Tabela de clientes
CREATE TABLE IF NOT EXISTS clientes (
  id            BIGSERIAL PRIMARY KEY,
  nome          TEXT NOT NULL,
  razao_social  TEXT,
  cnpj          TEXT,
  contato       TEXT,
  email         TEXT,
  telefone      TEXT,
  cidade        TEXT,
  uf            TEXT,
  forma_entrega TEXT DEFAULT 'ARKMEDS',
  link_arkmeds  TEXT,
  observacoes   TEXT,
  data_corte    TEXT,
  criado_em     TIMESTAMPTZ DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de arquivos
CREATE TABLE IF NOT EXISTS arquivos (
  id            BIGSERIAL PRIMARY KEY,
  cliente_id    BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  nome_original TEXT NOT NULL,
  nome_arquivo  TEXT NOT NULL,
  caminho_local TEXT,
  tipo          TEXT,
  tamanho       BIGINT,
  criado_em     TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de histórico
CREATE TABLE IF NOT EXISTS historico (
  id            BIGSERIAL PRIMARY KEY,
  cliente_id    BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  descricao     TEXT NOT NULL,
  criado_em     TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Realtime para todas as tabelas
ALTER PUBLICATION supabase_realtime ADD TABLE clientes;
ALTER PUBLICATION supabase_realtime ADD TABLE arquivos;
ALTER PUBLICATION supabase_realtime ADD TABLE historico;

-- ============================================================
-- DADOS: todos os clientes da planilha Email_de_clientes.xlsx
-- ============================================================
INSERT INTO clientes (nome, forma_entrega, observacoes) VALUES
('3R FERRAMENTARIA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('ACEARICA FREDERICO MISSNER','E-MAIL','VERIFICAR PLANILHA DO CLIENTE'),
('ACEST','FÍSICO','SEM PERIODICIDADE'),
('AGRO TROP UNID. LINHARES','FÍSICO-INTERNO / ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('ALLFLEX','ARKMEDS','NÃO COLOCAR O NÚMERO DA MÁQUINA NO LOCAL / VERIFICAR PLANILHA DO CLIENTE'),
('ALYA CONSTRUTORA','','SEM PERIODICIDADE'),
('ANDINA - JACAREPAGUÁ','GOOGLE DRIVE','ORGANIZAR CERTIFICADOS POR LOCAL'),
('ANDINA - RIBEIRÃO PRETO','ARKMEDS','UTILIZAR SOMENTE PADRÕES NACIONAIS / PADRÕES MRC / VERIFICAR PLANILHA DO CLIENTE'),
('ARTBOR','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('ATLANTIS','FÍSICO','COLOCAR UNIDADE -- PREVENTIVA EM TODOS'),
('AWE (PENHA LOG)','ARKMEDS','COLOCAR PLACA DO VEÍCULO'),
('AZIMUT','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('BORRAX','ARKMEDS','NORMAL TER CÓDIGOS DUPLICADOS / VERIFICAR PLANILHA DO CLIENTE'),
('BRASCOLA','ARKMEDS','TERMÔMETROS ERRO ADMISSÍVEL: 1 °C'),
('BRITÂNIA - CD','ARKMEDS','SEM ERRO ADMISSÍVEL / COLOCAR LOCAL: PRODUÇÃO'),
('BRITÂNIA - PRIME','ARKMEDS','SEM ERRO ADMISSÍVEL / COLOCAR LOCAL: PRODUÇÃO'),
('C&M LASER','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('CAMIL','ARKMEDS',''),
('CAMPOS NOVOS ENERGIA','ARKMEDS','SEM PERIODICIDADE'),
('CARBUSS','E-MAIL','VERIFICAR PLANILHA DO CLIENTE'),
('CASA DA INSTRUMENTAÇÃO','E-MAIL','VERIFICAR PROPRIETÁRIO'),
('CBS','ARKMEDS','SEMPRE CISABRASILE/ARKMEDS / SEM PERIODICIDADE / VERIFICAR PLANILHA DO CLIENTE'),
('CETENCO','E-MAIL',''),
('CHOCOLEITE','ARKMEDS','SE ATENTAR A PERIODICIDADE / CERTIFICADOS DEVEM TER NÚMERO DE SÉRIE'),
('CIA CANOINHAS','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('CISABRASILE','ARKMEDS','SEM PERIODICIDADE / VERIFICAR PLANILHA DO CLIENTE / ENVIAR A FICHA DE SERVIÇO EXTERNO POR E-MAIL'),
('CONSÓRCIO GÁS SUL','ARKMEDS','PROCEDIMENTO DEVE SAIR COMO IT-001'),
('CONTINENTAL','FÍSICO','Verificar e-mail para saber o proprietario'),
('COOPERATIVA ALFA','ARKMEDS','SEM PERIODICIDADE'),
('CRISTALPET ANTÔNIO CARLOS','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('CRN SAÚDE','ARKMEDS','CERTIFICADOS SEMPRE DEVEM SAIR COM FABRICANTE, MODELO E NÚMERO DE SÉRIE. CÓDIGO DEVE SER IGUAL O NÚMERO DE SÉRIE.'),
('CVI','ARKMEDS','PARA VÁLVULAS VERIFICAR PLANILHA DE CÓDIGOS'),
('DAGNONI','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('DASA','ARKMEDS','06 MESES DE PERIODICIDADE EM VOLUME / VERIFICAR PLANILHA DO CLIENTE'),
('DEMARCHI','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('DENTSCARE','ARKMEDS','TERMOHIGRÔMETRO ERRO ADMISSÍVEL 3° C E 9°%UR / VERIFICAR PLANILHA DO CLIENTE'),
('DESCARPACK','E-MAIL',''),
('DIAGNÓSTICOS DA AMÉRICA','ARKMEDS','06 MESES DE PERIODICIDADE EM VOLUME / VERIFICAR PLANILHA DO CLIENTE'),
('DOCOL','ARKMEDS','SEM ERRO ADMISSÍVEL / EMITIR SEM NÚMERO DE CERTIFICADO, SELO E DATADOR / VERIFICAR PLANILHA DO CLIENTE'),
('EBS','ARKMEDS','ERRO ADMISSÍVEL 3% / ERRO ADMISSÍVEL DE 10% PARA OS COLORÍMETROS / VERIFICAR SE É PRA EMITIR COMO VERSA/CÓDIGO DEVE SER O NÚMERO DE PATRIMÔNIO'),
('EMBRACO','ARKMEDS','EMITIR SEM NÚMERO DE CERTIFICADO E SELO E SEM PERIODICIDADE'),
('ENDRESS + HAUSER','ARKMEDS','VERIFICAR UNIDADE / VERIFICAR PLANILHA DO CLIENTE'),
('FALCON','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('FAST','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('FBM','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('FETTI','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('FIBERVILLE','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE / PLANILHA NOVA'),
('FIXSUL','ARKMEDS','MICROMETRO E HASTE (2 ANOS) E TRENA (1 ANO) / VERIFICAR PLANILHA DO CLIENTE'),
('FOUNTAIN','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('FUNDIÇÃO DE METAIS ROSIL','ARKMEDS','SEM PERIODICIDADE'),
('FUTURA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('G-MEYER','ARKMEDS','PERIODICIDADE DE 24 MESES'),
('GRUPO SOLAR - UNID. ARAPIRACA','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. BELÉM','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. CAF','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. JOÃO PESSOA','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. MACAÍBA','ARKMEDS','VER PLANILHA DE VENCIMENTOS / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. MACEIÓ','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. MARACANAÚ','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. SALVADOR','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. SÃO LUÍS','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. SUAPE','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. TERESINA','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('GRUPO SOLAR - UNID. VITÓRIA DA CONQUISTA','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('HABITASUL','ARKMEDS','VERIFICAR A PLANILHA DO CLIENTE'),
('HARD','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('HNK - BENEVIDES','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('HNK - PONTA GROSSA','ARKMEDS','ERRO ADMISSÍVEL TERMOHIGRÔMETRO: 1,3 °C / 10%'),
('HOSPITAL SANTA LUZIA','FÍSICO','06 MESES DE PERIODICIDADE EM VOLUME'),
('HRM MOLDES','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('IBT','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('INDUMAK','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('INDÚSTRIA DE BORRACHAS SR','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('INPLAVEL','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE / ERRO ADMISSÍVEL DE RÉGUAS: 0,8 mm'),
('INSIDE MEDICAL','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('INTERAMÉRICA','FÍSICO','PERIODICIDADE 6 MESES EM BALANÇAS'),
('ITAPOÁ TERMINAIS PORTUÁRIOS','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('JOARP','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('KELTEC','E-MAIL',''),
('KOWALSKY','ARKMEDS','ERRO ADMISSÍVEL PARA TERMÔMETRO É DE 1°C'),
('KRONA TUBOS E CONEXÕES','ARKMEDS','12 MESES PERIODICIDADE EM PAQUÍMETROS / VERIFICAR PLANILHA DO CLIENTE'),
('LABORATÓRIO CATARINENSE','ARKMEDS','VER LISTA DE BALANÇAS COM PERIODICIDADE / VERIFICAR PERIODICIDADE NA PASTA DO CLIENTE'),
('LABORATÓRIO SANDRINI','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('LABORATÓRIO SANTA LUZIA / DASA','ARKMEDS','06 MESES DE PERIODICIDADE EM VOLUME / VERIFICAR PLANILHA DO CLIENTE'),
('LABORSAD','FÍSICO',''),
('L''AQUAMARINE','E-MAIL','VERIFICAR PROPRIETÁRIO'),
('LEÃO - FAZENDA RIO GRANDE','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('LEÃO - FERNANDES PINHEIRO','ARKMEDS','MEDIDOR DE CAMPO MAGNÉTICO (FAIXA DE 1000 A 15000 GAUSS) / VERIFICAR PLANILHA DO CLIENTE'),
('LUZVILLE','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('MABRA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('MAC LASER','ARKMEDS','SEM PERIODICIDADE / VERIFICAR PLANILHA DO CLIENTE'),
('MADERO','FÍSICO',''),
('MAGNA COMPÓSITOS','ARKMEDS','SEM PERIODICIDADE'),
('MAGNA METÁLICOS','ARKMEDS','SEM PERIODICIDADE'),
('MAGNA MOLDES','ARKMEDS','SEM PERIODICIDADE'),
('MAGNA PLÁSTICO','ARKMEDS','SEM PERIODICIDADE'),
('MARCEGAGLIA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE / PRIORIDADE NO ENVIO DE CERTIFICADOS / NÃO COLOCAR DATADOR / PNP PERIODICIDADE 24 MESES / NÃO COLOCAR FAIXA CALIBRADA / MANÔMETRO PDMA-225 PERIODICIDADE 36 MESES'),
('MINÂNCORA','ARKMEDS','PERIODICIDADE VIDRARIA: 24 MESES / VERIFICAR PERIODICIDADE NA PASTA DO CLIENTE'),
('MINIPA','E-MAIL','VERIFICAR PROPRIETÁRIO'),
('MOINHO CIDADE BELLA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('MULTILOG','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('N & L','ARKMEDS',''),
('NAGBOR','FÍSICO','PROPRIETÁRIO NSO'),
('NIDEC','ARKMEDS','EMITIR SEM NÚMERO DE CERTIFICADO E SELO E SEM PERIODICIDADE'),
('NUTRIMENTAL','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('ORTOSUL','FÍSICO',''),
('PHS DO BRASIL','ARKMEDS','VERIFICAR PONTOS CALIBRADOS NA PLANILHA DE CLIENTES'),
('PLASTIBRAS','ARKMEDS','PRIORIDADE NO ENVIO DE CERTIFICADOS'),
('PLASTICOVILLE','ARKMEDS','CALIBRAÇÃO TERCEIRIZADA PERIODICIDADE DE 36 MESES'),
('PLASTPRACK','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('POMPÉIA ALIMENTOS','E-MAIL',''),
('PROTMOLDE','E-MAIL',''),
('PROTS','ARKMEDS','EQUIPAMENTOS DE LABORATÓRIOS SEM VALIDADE. PRESSÃO E TEMPERATURA 12 MESES'),
('QUÍMICA NOVA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('RANCHO BOM','ARKMEDS','COLOCAR O NOME DO BAIRRO COMO UNIDADE DA EMPRESA'),
('RB EXP. IMP. PRODUTOS DE BARBEAR','FÍSICO','TERMOHIGRÔMETROS PERIODICIDADE - 24 MESES'),
('REBICA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('REFRESCOS BANDEIRANTES','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('REFRESCOS RIO DE JANEIRO - DUQUE DE CAXIAS','GOOGLE DRIVE','ORGANIZAR CERTIFICADOS POR LOCAL'),
('REFRESCOS RIO DE JANEIRO - JACAREPAGUÁ','GOOGLE DRIVE','ORGANIZAR CERTIFICADOS POR LOCAL'),
('REFRESCOS RIO DE JANEIRO - RIBEIRÃO PRETO','ARKMEDS','UTILIZAR SOMENTE PADRÕES NACIONAIS / PADRÕES MRC / VERIFICAR PLANILHA DO CLIENTE'),
('REMBAL','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('RIBEIRO FERRAMENTARIA','ARKMEDS','CONTROLADOR DE TEMPERATURA N° ALEATÓRIO'),
('SAPORE','E-MAIL','ERRO ADMISSÍVEL TEMPERATURA: 2 ºC / VERIFICAR PLANILHA DO CLIENTE'),
('SAPORE (UNIDADE BMW)','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('SATAKE','E-MAIL','VERIFICAR ERROS ADMISSÍVEIS NAS PLANILHAS DO CLIENTE'),
('SCHULZ','ARKMEDS','PREENCHER PLANILHA DO CLIENTE'),
('SEPAT','FÍSICO',''),
('SERRANA','ARKMEDS','ERRO ADMISSÍVEL 3%'),
('SHALOM','E-MAIL',''),
('SIEMENS','ARKMEDS','NÃO CALIBRAR PONTO 0 / VERIFICAR PLANILHA DO CLIENTE'),
('SIMBIOSE','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('SINTEX','FÍSICO',''),
('SODEXO (BLUMENAU)','FÍSICO','VERIFICAR UNIDADE / PERIODICIDADE PARA TERMOMETRO 12 / VERIFICAR NA PLANILHA PONTOS CALIBRADOS TERMÔMETRO'),
('SODEXO (VIQUA - JOINVILLE)','FÍSICO',''),
('SODEXO (WHIRLPOOL)','E-MAIL',''),
('SPAL - OSASCO','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('SPAL - UNID CAMPO GRANDE','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL - UNID. ANTÔNIO CARLOS','ARKMEDS','SE TIVER SEM LOCAL COLOCAR: LABORATÓRIO / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / ATUALIZAR PLANILHA / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL - UNID. CURITIBA','ARKMEDS','COLOCAR LOCAL / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / PARA UNIDADES STS E ATM A PERIODICIDADE É DE 12 MESES, PARA PROVETAS É 6 MESES / ATUALIZAR PLANILHA / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL - UNID. ITABIRITO','ARKMEDS','COLOCAR LOCAL / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / ATUALIZAR PLANILHA / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL - UNID. MARÍLIA','FÍSICO','TERMOHIGRÔMETRO: ADMISSÍVEL 1 | 10 (COLOCAR PONTO 0°) / COLOCAR LOCAL: LINHA / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL - UNID. MARINGÁ','ARKMEDS','COLOCAR LOCAL / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / ATUALIZAR PLANILHA / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL - UNID. MOGI DAS CRUZES','ARKMEDS','COLOCAR LOCAL / VERIFICAR PLANILHA / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL - UNID. PORTO ALEGRE','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE / TERMOHIGRÔMETRO: ADMISSÍVEL 1,5 | 5 / COLOCAR LOCAL / NÃO MUDAR FAIXA DO EQUIPAMENTO / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('SPAL - UNID. PORTO REAL','ARKMEDS','COLOCAR LOCAL / PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('SPAL - UNID. SANTA MARIA','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02 / COLOCAR LOCAL / ATUALIZAR PLANILHA / VERIFICAR PLANILHA DO CLIENTE'),
('SPAL BLUMENAU','ARKMEDS','PHMETRO: OBRIGATÓRIO TER FAIXA PH 02'),
('STRAUHS','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('SUL CORTE','ARKMEDS','SEM PERIODICIDADE / CÓDIGO DO CLIENTE'),
('SURVISUL','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('TECNOPERFIL','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('TELEWORLD','E-MAIL','VERIFICAR PROPRIETÁRIO'),
('TRIUNFO','E-MAIL','MANDAR CERTIFICADOS POR E-MAIL / VERIFICAR ERRO NA PLANILHA'),
('ULTRAGÁZ','FÍSICO','MANÔMETRO PERIODICIDADE 72 MESES / COLOCAR DIÂMETRO E TIPO DE MOLA (EXTERNA OU INTERNA) NAS VÁLVULAS DE SEGURANÇA'),
('UNIDOCK''S','ARKMEDS','ERRO ADMISSÍVEL TEMPERATURA 1°C E UMIDADE 8%'),
('UNION MOLDES','ARKMEDS','PERIODICIDADE DE 24 MESES'),
('VMG','ARKMEDS','PERIODICIDADE DE PAQUIMETROS 12 MESES'),
('WELD VISION','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('WHITENESS DO BRASIL','ARKMEDS','TERMOHIGRÔMETRO ERRO ADMISSÍVEL 3° C E 9°%UR / VERIFICAR PLANILHA DO CLIENTE'),
('WOERNER','ARKMEDS','24 MESES PERIODICIDADE / VERIFICAR PLANILHA DO CLIENTE'),
('YPIÓCA','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE'),
('ZSG','ARKMEDS','VERIFICAR PLANILHA DO CLIENTE');

-- E-mails da aba "E-mails" (amostra representativa com e-mails conhecidos)
UPDATE clientes SET email = 'joece.nascimento@brascola.com.br' WHERE nome = 'BRASCOLA';
UPDATE clientes SET email = 'greice.buzzi@descarpack.com.br' WHERE nome = 'DESCARPACK';
UPDATE clientes SET email = 'augusto.oliveira@cetenco.com.br' WHERE nome = 'CETENCO';
UPDATE clientes SET email = 'qualidade2@plastibras.com.br' WHERE nome = 'PLASTIBRAS';
UPDATE clientes SET email = 'danilo.s.santana@nidec-ga.com' WHERE nome = 'EMBRACO';
UPDATE clientes SET email = 'tais.laurindo@nidec-ga.com' WHERE nome = 'NIDEC';
UPDATE clientes SET email = 'Gustavo.Pinto@kof.com.mx' WHERE nome = 'FOUNTAIN';
UPDATE clientes SET email = 'kleyton@joarp.com.br' WHERE nome = 'JOARP';
UPDATE clientes SET email = 'qualidade@weldvision.com.br' WHERE nome = 'WELD VISION';
UPDATE clientes SET email = 'fabricio.batista-sc@airliquide.com' WHERE nome LIKE '%ENDRESS%';
UPDATE clientes SET email = 'leticia.vieira@marcegaglia.com.br' WHERE nome = 'MARCEGAGLIA';
UPDATE clientes SET email = 'qualidade1@ibt.ind.br' WHERE nome = 'IBT';
UPDATE clientes SET email = 'qualidade@fiberville.com.br' WHERE nome = 'FIBERVILLE';
UPDATE clientes SET email = 'carlospadilha@hrmmoldes.com.br' WHERE nome = 'HRM MOLDES';
UPDATE clientes SET email = 'inspecao@minancora.com.br' WHERE nome = 'MINÂNCORA';
UPDATE clientes SET email = 'qualidade@multilog.com.br' WHERE nome = 'MULTILOG';
UPDATE clientes SET email = 'rodrigotavarodrigues@gmail.com' WHERE nome = 'LABORATÓRIO SANDRINI';
UPDATE clientes SET email = 'karina@moinhocidadebella.com.br' WHERE nome = 'MOINHO CIDADE BELLA';
UPDATE clientes SET email = 'qualidade@kowalsky.com.br' WHERE nome = 'KOWALSKY';
UPDATE clientes SET email = 'beatriz.orzechovicz@fgmdentalgroup.com' WHERE nome = 'DENTSCARE';
UPDATE clientes SET email = 'adm@dagnoni.ind.br' WHERE nome = 'DAGNONI';
UPDATE clientes SET email = 'osmair.campos@indumak.com.br' WHERE nome = 'INDUMAK';
UPDATE clientes SET email = 'lab@borrachassr.com.br' WHERE nome = 'INDÚSTRIA DE BORRACHAS SR';
UPDATE clientes SET email = 'claudia.cq@inplavel.com.br' WHERE nome = 'INPLAVEL';
UPDATE clientes SET email = 'nfe@inside-medical.com' WHERE nome = 'INSIDE MEDICAL';
UPDATE clientes SET email = 'jonathas.chikazawa@portoitapoa.com' WHERE nome = 'ITAPOÁ TERMINAIS PORTUÁRIOS';
UPDATE clientes SET email = 'celso@satake.com.br' WHERE nome = 'SATAKE';
UPDATE clientes SET email = 'alice@triunfodobrasil.com' WHERE nome = 'TRIUNFO';
UPDATE clientes SET email = 'juliana@shalompolimentos.com.br' WHERE nome = 'SHALOM';
UPDATE clientes SET email = 'gabriel.hastreiter@oxford.ind.br' WHERE nome LIKE '%OXFORD%';
UPDATE clientes SET email = 'ediney.reis@bioma.ind.br' WHERE nome = 'SIMBIOSE';
UPDATE clientes SET email = 'bruno.silva@schulz.com.br' WHERE nome = 'SCHULZ';
UPDATE clientes SET email = 'vanderley.dagnoni@busscar.com.br' WHERE nome = 'CARBUSS';
UPDATE clientes SET email = 'janio@bestfoodsbrasil.com' WHERE nome LIKE '%FAST%';
UPDATE clientes SET email = 'qualidade@falcon-eletronica.com.br' WHERE nome = 'FALCON';
UPDATE clientes SET email = 'vanderlei@fbmoldes.com.br' WHERE nome = 'FBM';
UPDATE clientes SET email = 'qualidade@zkaluminio.ind.br' WHERE nome = 'FETTI';
UPDATE clientes SET email = 'qualidade@fiberville.com.br' WHERE nome = 'FIBERVILLE';
UPDATE clientes SET email = 'nfe@fixsul.com.br' WHERE nome = 'FIXSUL';
UPDATE clientes SET email = 'qualidade1@futurafundicao.com.br' WHERE nome = 'FUTURA';
UPDATE clientes SET email = 'qualidade@gmeyerequipamentos.com.br' WHERE nome = 'G-MEYER';
UPDATE clientes SET email = 'suhellen.barcelos@habitasul.com.br' WHERE nome = 'HABITASUL';
UPDATE clientes SET email = 'isabel.cardoso@hard.com.br' WHERE nome = 'HARD';
UPDATE clientes SET email = 'douglas.hedler@krona.com.br' WHERE nome = 'KRONA TUBOS E CONEXÕES';
UPDATE clientes SET email = 'qualidade1@woerner.com.br' WHERE nome = 'WOERNER';
UPDATE clientes SET email = 'wellington@plasticoville.com.br' WHERE nome = 'PLASTICOVILLE';
UPDATE clientes SET email = 'qualidade@survisul.com.br' WHERE nome = 'SURVISUL';
UPDATE clientes SET email = 'qualidade@tecnoperfil.com.br' WHERE nome = 'TECNOPERFIL';
UPDATE clientes SET email = 'comercial.jvl@teleworld.com.br' WHERE nome = 'TELEWORLD';
UPDATE clientes SET email = 'dcguesser@minipa.com.br' WHERE nome = 'MINIPA';
UPDATE clientes SET email = 'sarah@aikonempreendimentos.com.br' WHERE nome = 'L''AQUAMARINE';
UPDATE clientes SET email = 'comercial@casadainstrumentacao.com' WHERE nome = 'CASA DA INSTRUMENTAÇÃO';
UPDATE clientes SET email = 'fabricio.rosa@veolia.com' WHERE nome LIKE '%SODEXO%BLUMENAU%';
UPDATE clientes SET email = 'mariana.kampa@triunfodobrasil.com' WHERE nome = 'TRIUNFO';
UPDATE clientes SET email = 'cq@beloburger.com.br' WHERE nome = 'POMPÉIA ALIMENTOS';
UPDATE clientes SET email = 'contato@protmolde.com.br' WHERE nome = 'PROTMOLDE';
UPDATE clientes SET email = 'ahanada@prots.com.br' WHERE nome = 'PROTS';
UPDATE clientes SET email = 'gabriele.steinbraenner@quimicanovabrasil.com.br' WHERE nome = 'QUÍMICA NOVA';
UPDATE clientes SET email = 'controlealimentos@ranchobom.com.br' WHERE nome = 'RANCHO BOM';
UPDATE clientes SET email = 'mylena.arruda@rebic.com.br' WHERE nome = 'REFRESCOS BANDEIRANTES';
UPDATE clientes SET email = 'rafaela@fribeiro.com.br' WHERE nome = 'RIBEIRO FERRAMENTARIA';
UPDATE clientes SET email = 'cristiane.carli@sapore.com.br' WHERE nome LIKE '%SAPORE%';
UPDATE clientes SET email = 'manufatura@strauhs.com.br' WHERE nome = 'STRAUHS';
UPDATE clientes SET email = 'fabio.bastos@kof.com.mx' WHERE nome = 'SPAL - OSASCO';
UPDATE clientes SET email = 'janice.batista@kof.com.mx' WHERE nome = 'SPAL BLUMENAU';
UPDATE clientes SET email = 'qualidade@vmgtransportes.com.br' WHERE nome = 'VMG';
UPDATE clientes SET email = 'qualidade1@woerner.com.br' WHERE nome = 'WOERNER';

-- Data de corte para clientes da Planilha3
UPDATE clientes SET data_corte = 'Dia 20' WHERE nome = 'ATLANTIS';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'BRASCOLA';
UPDATE clientes SET data_corte = 'Dia 20' WHERE nome = 'EMBRACO';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'LEÃO - FAZENDA RIO GRANDE';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome LIKE '%LEÃO%FERNANDES%';
UPDATE clientes SET data_corte = 'Dia 20' WHERE nome = 'SIEMENS';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'HABITASUL';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'REFRESCOS BANDEIRANTES';
UPDATE clientes SET data_corte = 'Dia 10' WHERE nome = 'DOCOL';
UPDATE clientes SET data_corte = 'Dia 20' WHERE nome = 'EBS';
UPDATE clientes SET data_corte = 'Dia 24' WHERE nome LIKE '%CRISTALPET%';
UPDATE clientes SET data_corte = 'Dia 20' WHERE nome LIKE 'DENTSCARE';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'CISABRASILE';
UPDATE clientes SET data_corte = 'Dia 20' WHERE nome = 'ENDRESS + HAUSER';
UPDATE clientes SET data_corte = 'Dia 20' WHERE nome LIKE 'FOUNTAIN%';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'CONSÓRCIO GÁS SUL';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome LIKE '%GRUPO SOLAR%';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome LIKE 'SPAL%';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'WOERNER';
UPDATE clientes SET data_corte = 'Dia 25' WHERE nome = 'UNION MOLDES';
